spring.application.name=SafeZone-Backend

# puerto del backend, se puede cambiar si quieres en caso este en uso este
server.port=8082

#swagger para tener la documentacion de los endpoints, get,post y esas cosas
springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false
