spring.application.name=SafeZone-Backend

# puerto del backend, se puede cambiar si quieres en caso este en uso este
server.port=8082

#swagger para tener la documentacion de los endpoints, get,post y esas cosas
springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false

# mysql driver / variables de entorno
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/safezonedb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/Lima}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:EspirituxD.1}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# flyway para que el asistente pueda consultar toda la estructura de la bd sin necesidad de estar exportandolo, 
# y para eso leera las variables de entorno de las credenciales de la BD
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true
