-- Normaliza tipos de violencia historicos a codigos oficiales.
-- Codigos oficiales: FISICA, PSICOLOGICA, SEXUAL, ECONOMICA, PATRIMONIAL, DIGITAL, OTRA.

UPDATE denuncia
SET tipo_violencia = CASE
  WHEN UPPER(TRIM(tipo_violencia)) IN ('FISICA', 'FÍSICA', 'VIOLENCIA FISICA', 'VIOLENCIA FÍSICA') THEN 'FISICA'
  WHEN UPPER(TRIM(tipo_violencia)) IN ('PSICOLOGICA', 'PSICOLÓGICA', 'VIOLENCIA PSICOLOGICA', 'VIOLENCIA PSICOLÓGICA', 'EMOCIONAL', 'VIOLENCIA EMOCIONAL') THEN 'PSICOLOGICA'
  WHEN UPPER(TRIM(tipo_violencia)) IN ('SEXUAL', 'VIOLENCIA SEXUAL') THEN 'SEXUAL'
  WHEN UPPER(TRIM(tipo_violencia)) IN ('ECONOMICA', 'ECONÓMICA', 'VIOLENCIA ECONOMICA', 'VIOLENCIA ECONÓMICA') THEN 'ECONOMICA'
  WHEN UPPER(TRIM(tipo_violencia)) IN ('PATRIMONIAL', 'VIOLENCIA PATRIMONIAL') THEN 'PATRIMONIAL'
  WHEN UPPER(TRIM(tipo_violencia)) IN ('DIGITAL', 'VIOLENCIA DIGITAL', 'CIBERNETICA', 'CIBERNÉTICA', 'VIRTUAL') THEN 'DIGITAL'
  ELSE 'OTRA'
END
WHERE tipo_violencia IS NOT NULL AND TRIM(tipo_violencia) <> '';

UPDATE pre_denuncia
SET tipo_violencia = CASE
  WHEN UPPER(TRIM(tipo_violencia)) IN ('FISICA', 'FÍSICA', 'VIOLENCIA FISICA', 'VIOLENCIA FÍSICA') THEN 'FISICA'
  WHEN UPPER(TRIM(tipo_violencia)) IN ('PSICOLOGICA', 'PSICOLÓGICA', 'VIOLENCIA PSICOLOGICA', 'VIOLENCIA PSICOLÓGICA', 'EMOCIONAL', 'VIOLENCIA EMOCIONAL') THEN 'PSICOLOGICA'
  WHEN UPPER(TRIM(tipo_violencia)) IN ('SEXUAL', 'VIOLENCIA SEXUAL') THEN 'SEXUAL'
  WHEN UPPER(TRIM(tipo_violencia)) IN ('ECONOMICA', 'ECONÓMICA', 'VIOLENCIA ECONOMICA', 'VIOLENCIA ECONÓMICA') THEN 'ECONOMICA'
  WHEN UPPER(TRIM(tipo_violencia)) IN ('PATRIMONIAL', 'VIOLENCIA PATRIMONIAL') THEN 'PATRIMONIAL'
  WHEN UPPER(TRIM(tipo_violencia)) IN ('DIGITAL', 'VIOLENCIA DIGITAL', 'CIBERNETICA', 'CIBERNÉTICA', 'VIRTUAL') THEN 'DIGITAL'
  ELSE 'OTRA'
END
WHERE tipo_violencia IS NOT NULL AND TRIM(tipo_violencia) <> '';
